version: 0.2

phases:
  install:
    commands:
      - echo Installing NVM...
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install 16.17.1
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - . ~/.nvm/nvm.sh
      - nvm use 16.17.1
      - echo Compiling the React code
      - npm run build
  build:
    commands:
      - echo Build started on `date`
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: build
