version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'  # or 'dist' or whatever your build output directory is
